import { config } from "dotenv";

config({ path: ".env.local" });

import { faker } from "@faker-js/faker";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import {
  analysisItems,
  diffSuggestions,
  type NewAnalysisItem,
  type NewDiffSuggestion,
  type NewSubmission,
  submissions,
} from "./schema";

// ---------------------------------------------------------------------------
// Seed data pools
// ---------------------------------------------------------------------------

const LANGUAGES = [
  "javascript",
  "typescript",
  "python",
  "java",
  "php",
  "csharp",
  "cpp",
  "ruby",
  "go",
  "bash",
];

const ROAST_QUOTES = [
  "this code looks like it was written during a power outage... in 2005.",
  "i've seen better architecture in a house of cards.",
  "whoever wrote this clearly learned to code from a fortune cookie.",
  "this is what happens when you skip the fundamentals.",
  "i'd rather read the terms and conditions than maintain this.",
  "even stackoverflow would reject this question.",
  "this code has more red flags than a bull fight.",
  "i'm not saying it's bad, i'm saying it's aggressively bad.",
  "this is the spaghetti western of codebases.",
  "your future self will despise your current self for this.",
  "i've seen cleaner code in a 2003 php guestbook.",
  "this wouldn't pass a code review at a startup with two employees.",
  "somewhere, a senior dev is crying and doesn't know why.",
  "this code is technically not illegal, but it should be.",
  "congratulations, you've reinvented the wheel — badly.",
  "this reads like it was generated by a very tired ai.",
  "the git blame on this would cause physical pain.",
  "not even the compiler deserves this.",
  "this is why we have naming conventions.",
  "i've seen more structure in a mosh pit.",
  "this code works exactly once, under perfect conditions, never again.",
  "every variable name here is a war crime.",
  "i feel my IQ dropping just reading this.",
  "the cyclomatic complexity here rivals a soap opera plot.",
  "this is what 'move fast and break things' looks like in practice.",
  "future devs will find this and assume it was a practical joke.",
  "this is the coding equivalent of eating cereal with orange juice.",
  "i've seen more comments in a mime convention.",
  "this function does six things and none of them well.",
  "congratulations on discovering a new anti-pattern.",
];

const CRITICAL_ISSUES = [
  {
    title: "using var instead of const/let",
    description:
      "var is function-scoped and leads to hoisting bugs. use const by default, let when reassignment is needed.",
  },
  {
    title: "no error handling whatsoever",
    description:
      "this code assumes nothing will ever go wrong. it will go wrong.",
  },
  {
    title: "hardcoded credentials in source code",
    description:
      "passwords and api keys should never appear in source. use environment variables.",
  },
  {
    title: "sql injection vulnerability",
    description:
      "string concatenation in queries is a direct invitation for sql injection. use parameterized queries.",
  },
  {
    title: "infinite loop risk",
    description:
      "the loop termination condition is unreachable under certain inputs. this will hang.",
  },
  {
    title: "unhandled promise rejections",
    description:
      "async calls without catch blocks will silently fail and leave state corrupted.",
  },
  {
    title: "mutation of function arguments",
    description:
      "modifying the input object directly causes invisible side effects at the call site.",
  },
  {
    title: "deeply nested callbacks",
    description:
      "callback hell is a solved problem. use async/await or promise chaining.",
  },
  {
    title: "memory leak via event listeners",
    description:
      "listeners added without a corresponding removeEventListener will accumulate forever.",
  },
  {
    title: "using == instead of ===",
    description:
      "loose equality causes type coercion. 0 == false is true here. you probably don't want that.",
  },
];

const WARNING_ISSUES = [
  {
    title: "imperative loop pattern",
    description:
      "for loops are verbose and error-prone. use .reduce() or .map() for cleaner transformations.",
  },
  {
    title: "magic numbers throughout",
    description:
      "what does 86400 mean? extract constants with descriptive names.",
  },
  {
    title: "function doing too many things",
    description:
      "this function has 4 distinct responsibilities. split it by concern.",
  },
  {
    title: "deeply nested conditionals",
    description:
      "consider early returns to flatten this logic. the nesting depth is unnecessary.",
  },
  {
    title: "inconsistent naming conventions",
    description:
      "camelCase and snake_case are mixed freely. pick one and commit.",
  },
  {
    title: "commented-out dead code",
    description:
      "dead code in comments is noise. if you need it, git has your back.",
  },
  {
    title: "no input validation",
    description:
      "this function trusts whatever it receives. at minimum check for null/undefined.",
  },
  {
    title: "repeated logic with no abstraction",
    description:
      "the same 8-line block appears 3 times. extract it into a helper.",
  },
  {
    title: "boolean parameter flag",
    description:
      "a boolean arg that changes function behavior is a sign it should be two functions.",
  },
  {
    title: "string concatenation for i18n",
    description:
      "building user-facing strings with + is fragile and untranslatable.",
  },
];

const GOOD_ISSUES = [
  {
    title: "clear naming conventions",
    description:
      "variable and function names are descriptive and self-documenting. communicates intent.",
  },
  {
    title: "single responsibility",
    description:
      "the function does one thing well — no side effects, no mixed concerns.",
  },
  {
    title: "good use of early returns",
    description:
      "guard clauses at the top flatten the logic and reduce cognitive load.",
  },
  {
    title: "proper use of const",
    description:
      "immutable bindings used throughout. signals intent and prevents reassignment bugs.",
  },
  {
    title: "small, focused functions",
    description:
      "each function fits on one screen. composable and easy to test in isolation.",
  },
];

// ---------------------------------------------------------------------------
// Code snippet generators per language
// ---------------------------------------------------------------------------

function generateCodeSnippet(language: string): string[] {
  const snippets: Record<string, string[][]> = {
    javascript: [
      [
        "var total = 0;",
        "for (var i = 0; i < items.length; i++) {",
        "  total = total + items[i].price;",
        "}",
        "return total;",
      ],
      [
        "function getUser(id) {",
        "  var data = db.query('SELECT * FROM users WHERE id = ' + id);",
        "  return data;",
        "}",
      ],
      [
        "var password = 'supersecret123';",
        "var apiKey = 'sk-abc123xyz';",
        "fetch('/api/login?pass=' + password);",
      ],
      [
        "function doEverything(data, flag) {",
        "  if (flag == true) {",
        "    // process",
        "  } else {",
        "    // also process but differently",
        "  }",
        "}",
      ],
      [
        "setTimeout(function() {",
        "  setTimeout(function() {",
        "    setTimeout(function() {",
        "      doTheThing();",
        "    }, 1000);",
        "  }, 1000);",
        "}, 1000);",
      ],
    ],
    typescript: [
      [
        "function calculateTotal(items: any[]): any {",
        "  let total: any = 0;",
        "  for (let i = 0; i < items.length; i++) {",
        "    total = total + items[i].price;",
        "  }",
        "  return total;",
        "}",
      ],
      [
        "const handler = async (req: any, res: any) => {",
        "  const user = await db.findUser(req.body.id);",
        "  res.json(user);",
        "};",
      ],
      ["type UserData = {", "  id: any;", "  name: any;", "  data: any;", "};"],
      [
        "class UserService {",
        "  private db: any;",
        "  constructor() { this.db = new Database(); }",
        "  getUser(id: string) { return this.db.query(id); }",
        "  setUser(u: any) { this.db.set(u); }",
        "  deleteUser(id: string) { this.db.del(id); }",
        "  updateUser(u: any) { this.db.upd(u); }",
        "}",
      ],
    ],
    python: [
      [
        "def get_user(id):",
        "    query = 'SELECT * FROM users WHERE id = ' + str(id)",
        "    return db.execute(query)",
      ],
      [
        "password = 'admin123'",
        "secret = 'my-secret-key'",
        "print('Connecting with password: ' + password)",
      ],
      [
        "def process(data, flag, mode, extra, debug):",
        "    if flag:",
        "        if mode == 1:",
        "            if extra:",
        "                if debug:",
        "                    print(data)",
      ],
      [
        "result = []",
        "for i in range(len(items)):",
        "    for j in range(len(items[i])):",
        "        result.append(items[i][j])",
        "return result",
      ],
    ],
    java: [
      [
        "public String getUser(String id) {",
        '  String query = "SELECT * FROM users WHERE id = " + id;',
        "  return db.execute(query);",
        "}",
      ],
      [
        "public void processAll(List data) {",
        "  for (int i = 0; i < data.size(); i++) {",
        "    for (int j = 0; j < ((List)data.get(i)).size(); j++) {",
        "      System.out.println(((List)data.get(i)).get(j));",
        "    }",
        "  }",
        "}",
      ],
      [
        "static String PASSWORD = 'root123';",
        "static String HOST = 'prod-db.internal';",
        "static int PORT = 5432;",
      ],
    ],
    php: [
      [
        "<?php",
        "$id = $_GET['id'];",
        "$query = 'SELECT * FROM users WHERE id = ' . $id;",
        "$result = mysql_query($query);",
        "?>",
      ],
      [
        "<?php",
        "$password = 'admin';",
        "include('config.php');",
        "eval($_POST['code']);",
        "?>",
      ],
    ],
    csharp: [
      [
        "public string GetUser(string id) {",
        '  var query = "SELECT * FROM Users WHERE Id = " + id;',
        "  return db.ExecuteScalar(query).ToString();",
        "}",
      ],
      [
        "void DoEverything(object data) {",
        "  ProcessData(data);",
        "  ValidateData(data);",
        "  SaveData(data);",
        "  NotifyUser(data);",
        "  LogActivity(data);",
        "  SendEmail(data);",
        "}",
      ],
    ],
    cpp: [
      [
        "char* getInput() {",
        "  char buffer[10];",
        "  gets(buffer);",
        "  return buffer;",
        "}",
      ],
      [
        "int* createArray(int size) {",
        "  int* arr = new int[size];",
        "  return arr;",
        "  // forgot delete[]",
        "}",
      ],
    ],
    ruby: [
      ["def get_user(id)", '  User.where("id = #{id}").first', "end"],
      [
        "class God",
        "  def initialize",
        "    @db = Database.new",
        "    @cache = Cache.new",
        "    @mailer = Mailer.new",
        "    @logger = Logger.new",
        "  end",
        "  def do_everything(data); end",
        "end",
      ],
    ],
    go: [
      [
        "func getUser(id string) User {",
        '  query := "SELECT * FROM users WHERE id = " + id',
        "  row := db.QueryRow(query)",
        "  var u User",
        "  row.Scan(&u)",
        "  return u",
        "}",
      ],
      [
        "func process(data []byte) {",
        "  _ = json.Unmarshal(data, &result)",
        "  // ignoring the error intentionally",
        "}",
      ],
    ],
    bash: [
      [
        "#!/bin/bash",
        "PASSWORD=supersecret",
        "curl -u admin:$PASSWORD http://prod-server/api",
      ],
      ["#!/bin/bash", "rm -rf $1/*", "# what could go wrong?"],
    ],
  };

  const langSnippets = snippets[language] ?? snippets.javascript;
  return faker.helpers.arrayElement(langSnippets);
}

type DiffLine = { lineType: "added" | "removed" | "context"; content: string };

function generateDiffLines(language: string): DiffLine[] {
  const diffs: Record<string, DiffLine[]> = {
    javascript: [
      { lineType: "context", content: "function calculateTotal(items) {" },
      { lineType: "removed", content: "  var total = 0;" },
      {
        lineType: "removed",
        content: "  for (var i = 0; i < items.length; i++) {",
      },
      { lineType: "removed", content: "    total = total + items[i].price;" },
      { lineType: "removed", content: "  }" },
      { lineType: "removed", content: "  return total;" },
      {
        lineType: "added",
        content: "  return items.reduce((sum, item) => sum + item.price, 0);",
      },
      { lineType: "context", content: "}" },
    ],
    typescript: [
      { lineType: "context", content: "function getUser(id: any): any {" },
      {
        lineType: "removed",
        content: "  return db.query('SELECT * FROM users WHERE id = ' + id);",
      },
      {
        lineType: "added",
        content:
          "  return db.query('SELECT * FROM users WHERE id = $1', [id]);",
      },
      { lineType: "context", content: "}" },
    ],
    python: [
      { lineType: "context", content: "def get_user(id):" },
      {
        lineType: "removed",
        content: "    query = 'SELECT * FROM users WHERE id = ' + str(id)",
      },
      {
        lineType: "added",
        content: "    query = 'SELECT * FROM users WHERE id = %s'",
      },
      { lineType: "added", content: "    return db.execute(query, (id,))" },
      { lineType: "removed", content: "    return db.execute(query)" },
    ],
    java: [
      { lineType: "context", content: "public User getUser(String id) {" },
      {
        lineType: "removed",
        content: '  String q = "SELECT * FROM users WHERE id = " + id;',
      },
      { lineType: "removed", content: "  return db.execute(q);" },
      { lineType: "added", content: "  return db.findById(id).orElseThrow();" },
      { lineType: "context", content: "}" },
    ],
  };

  const lines = diffs[language] ?? diffs.javascript;
  return lines;
}

// ---------------------------------------------------------------------------
// Main seed function
// ---------------------------------------------------------------------------

async function seed() {
  const client = postgres(process.env.DATABASE_URL as string);
  const db = drizzle(client, { casing: "snake_case" });

  console.log("🌱 Seeding database...");

  // Clear existing data
  await db.delete(diffSuggestions);
  await db.delete(analysisItems);
  await db.delete(submissions);
  console.log("  ✓ Cleared existing data");

  const TOTAL = 100;

  for (let i = 0; i < TOTAL; i++) {
    const language = faker.helpers.arrayElement(LANGUAGES);
    const codeLines = generateCodeSnippet(language);
    const roastMode = faker.datatype.boolean({ probability: 0.4 });
    // Skew scores low — it's a shame leaderboard
    const score = faker.number
      .float({ min: 0.5, max: 10, fractionDigits: 2 })
      .toFixed(2);
    const roastQuote = faker.helpers.arrayElement(ROAST_QUOTES);
    const createdAt = faker.date.between({
      from: new Date("2025-01-01"),
      to: new Date(),
    });

    const submission: NewSubmission = {
      code: codeLines.join("\n"),
      language,
      linesCount: codeLines.length,
      roastMode,
      score,
      roastQuote,
      createdAt,
    };

    const [inserted] = await db
      .insert(submissions)
      .values(submission)
      .returning({ id: submissions.id });

    // 2–4 analysis items per submission
    const itemCount = faker.number.int({ min: 2, max: 4 });
    const criticalPool = faker.helpers.shuffle([...CRITICAL_ISSUES]);
    const warningPool = faker.helpers.shuffle([...WARNING_ISSUES]);
    const goodPool = faker.helpers.shuffle([...GOOD_ISSUES]);

    const items: NewAnalysisItem[] = [];

    // Always at least 1 critical or warning
    const numCritical = faker.number.int({
      min: 1,
      max: Math.min(2, itemCount - 1),
    });
    const numWarning = faker.number.int({
      min: 0,
      max: Math.min(1, itemCount - numCritical),
    });
    const numGood = itemCount - numCritical - numWarning;

    for (let c = 0; c < numCritical; c++) {
      const issue = criticalPool[c % criticalPool.length];
      items.push({
        submissionId: inserted.id,
        severity: "critical",
        title: issue.title,
        description: issue.description,
        sortOrder: items.length,
      });
    }
    for (let w = 0; w < numWarning; w++) {
      const issue = warningPool[w % warningPool.length];
      items.push({
        submissionId: inserted.id,
        severity: "warning",
        title: issue.title,
        description: issue.description,
        sortOrder: items.length,
      });
    }
    for (let g = 0; g < numGood; g++) {
      const issue = goodPool[g % goodPool.length];
      items.push({
        submissionId: inserted.id,
        severity: "good",
        title: issue.title,
        description: issue.description,
        sortOrder: items.length,
      });
    }

    await db.insert(analysisItems).values(items);

    // Diff suggestions
    const diffLines = generateDiffLines(language);
    const diffRows: NewDiffSuggestion[] = diffLines.map((line, idx) => ({
      ...line,
      submissionId: inserted.id,
      lineNumber: idx + 1,
    }));
    await db.insert(diffSuggestions).values(diffRows);
  }

  console.log(
    `  ✓ Inserted ${TOTAL} submissions with analysis items and diff suggestions`
  );
  console.log("🎉 Seed complete!");

  await client.end();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
